# Generated by Django 5.2.6 on 2025-09-28 23:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('exercise_type', models.CharField(choices=[('strength', 'Strength Training'), ('cardio', 'Cardio'), ('flexibility', 'Flexibility'), ('balance', 'Balance')], max_length=20)),
                ('equipment_needed', models.TextField(blank=True)),
                ('difficulty_level', models.IntegerField(help_text='Difficulty level from 1 (easy) to 5 (hard)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('muscle_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workout_program.musclegroup')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.IntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('fitness_level', models.IntegerField(blank=True, help_text='Current fitness level from 1 (beginner) to 5 (advanced)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('goals', models.TextField(blank=True, help_text='Fitness goals')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('program_type', models.CharField(choices=[('muscle', 'Muscle Building'), ('weight_loss', 'Weight Loss'), ('cardio', 'Cardio Training'), ('general', 'General Fitness'), ('strength', 'Strength Training')], max_length=20)),
                ('duration_weeks', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('difficulty_level', models.IntegerField(help_text='Program difficulty level from 1 (easy) to 5 (hard)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('day_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_days', to='workout_program.workoutprogram')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('program', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('repetitions', models.IntegerField(help_text='Reps per set', validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Duration in minutes (for cardio exercises)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg (for strength exercises)', max_digits=5, null=True)),
                ('rest_seconds', models.IntegerField(default=60, help_text='Rest time between sets in seconds', validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.IntegerField(default=1, help_text='Order of exercise in the session')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_program.exercise')),
                ('workout_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to='workout_program.workoutday')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserWorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('completed_sets', models.IntegerField(blank=True, null=True)),
                ('completed_reps', models.IntegerField(blank=True, null=True)),
                ('completed_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workout_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_program.workoutday')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_program.workoutprogram')),
                ('workout_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_program.workoutsession')),
            ],
        ),
    ]
